services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    environment:
      - VITE_API_URL=/api
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build: ./backend
    environment:
      - NODE_ENV=production
      - PORT=8000
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge