version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - target: 80
        published: 80
        protocol: TCP
    depends_on:
      - frontend
      - backend-fastapi
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: /api  # API calls will be proxied by nginx
        VITE_DEBUG: "false"
        VITE_LOG_LEVEL: WARN
    networks:
      - app-network
    restart: unless-stopped

  backend-fastapi:
    build: ./backend-fastapi
    environment:
      - PYTHONPATH=/app
      - DEBUG=ON
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge