services:
  nginx:
    build: ./nginx
    ports:
      - target: 80
        published: 80
        protocol: TCP
      - target: 443
        published: 443
        protocol: TCP
    depends_on:
      - frontend
      - backend-fastapi  # Updated to match service name
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    environment:
      - VITE_API_URL=/api
    networks:
      - app-network
    restart: unless-stopped

  # Updated backend service to use FastAPI instead of Node.js
  backend-fastapi:  # Changed service name for clarity
    build: ./backend-fastapi
    ports:
      - target: 8000
        published: 8000
        protocol: TCP
    environment:
      - PYTHONPATH=/app
      - DEBUG=OFF
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge